// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9YMJuUl0mMxHfR4pp_FHfVzwRAwRrySc',
    appId: '1:303250406776:web:43960afa217061bdb25c8d',
    messagingSenderId: '303250406776',
    projectId: 'chickstell-fe495',
    authDomain: 'chickstell-fe495.firebaseapp.com',
    storageBucket: 'chickstell-fe495.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEM1e_6xvtJW4pgieIRDqO14yEo13DBf4',
    appId: '1:303250406776:android:f939a7268ef3138cb25c8d',
    messagingSenderId: '303250406776',
    projectId: 'chickstell-fe495',
    storageBucket: 'chickstell-fe495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIZiT3QIVZ0Twblx2s8OLkP9p4NhegLs',
    appId: '1:303250406776:ios:7a00ad52f3099d17b25c8d',
    messagingSenderId: '303250406776',
    projectId: 'chickstell-fe495',
    storageBucket: 'chickstell-fe495.firebasestorage.app',
    iosClientId: '303250406776-j3macl1mv08d0ocppu69al6qvod8ua1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chickStellView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIZiT3QIVZ0Twblx2s8OLkP9p4NhegLs',
    appId: '1:303250406776:ios:7a00ad52f3099d17b25c8d',
    messagingSenderId: '303250406776',
    projectId: 'chickstell-fe495',
    storageBucket: 'chickstell-fe495.firebasestorage.app',
    iosClientId: '303250406776-j3macl1mv08d0ocppu69al6qvod8ua1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chickStellView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9YMJuUl0mMxHfR4pp_FHfVzwRAwRrySc',
    appId: '1:303250406776:web:a56848022c3b0ec4b25c8d',
    messagingSenderId: '303250406776',
    projectId: 'chickstell-fe495',
    authDomain: 'chickstell-fe495.firebaseapp.com',
    storageBucket: 'chickstell-fe495.firebasestorage.app',
  );
}
